# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf34f21d35b958de0ed9cfe3598c6caf3c176753c31a5302a0d519bb7ca6c9f6d3cfc7a3557c81ea2a24891ed82c3ea9d830110718c46c95f9cf2f019345b617

test:
  secret_key_base: 3e6c857ad6a491de12554c470f37131b2f3dea3cb690fa6eac2839243eee72aee373aac01b4099ef9b84a114fa5bc8554d1924c26f5e76be045cfb35726287f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
